services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6378
    networks:
      - app_network
    depends_on:
      - redis
    volumes:
      - ./containers:/app/containers:z
      - ./data:/app/data:z
      - /baixo/downloads:/baixo/downloads:z
      - /var/run/docker.sock:/var/run/docker.sock:z
    restart: no
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"

  redis:
    image: redis:alpine
    command: redis-server --port 6378
    volumes:
      - redis_data:/data
    networks:
      - app_network
    ports:
      - "6378:6378"
    restart: no

networks:
  app_network:
    driver: bridge

volumes:
  redis_data: