[supervisord]
nodaemon=true

[program:Xvfb]
command=Xvfb :99 -screen 0 1280x720x24
autostart=true
autorestart=true

[program:x11vnc]
command=x11vnc -display :99 -forever -nopw
autostart=true
autorestart=true

[program:squid]
command=/usr/sbin/squid -N -f /etc/squid/squid.conf
autostart=true
autorestart=true

[program:chrome]
command=google-chrome --no-sandbox --disable-dev-shm-usage --remote-debugging-port=9222 \
       --user-data-dir=/root/chrome-profile --display=:99 --window-size=1280,720 \
       --no-first-run --no-default-browser-check \
       --proxy-server="http://127.0.0.1:3128" \
       --downloads-directory=/root/Downloads \
       https://www.scopus.com
autostart=true
autorestart=true

[program:novnc]
command=/root/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autostart=true
autorestart=true