[supervisord]
nodaemon=true
user=root

[program:chromium]
command=xvfb-run --server-num=99 --server-args="-screen 0 1280x720x24 -ac -nolisten tcp" openbox --config-file /root/.config/openbox/rc.xml --startup /usr/local/bin/start-chromium.sh
autostart=true
autorestart=true
priority=10
startsecs=5
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:x11vnc]
command=bash -c "sleep 2 && x11vnc -display :99 -forever -nopw"
autostart=true
autorestart=true
priority=100
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:squid]
command=/usr/sbin/squid -N -f /etc/squid/squid.conf
autostart=true
autorestart=true
priority=100
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:novnc]
command=/root/noVNC/utils/novnc_proxy --vnc localhost:5900 --listen 6080
autostart=true
autorestart=true
priority=100
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0